from . import utils as utils

def ratio(s1, s2): ...
def partial_ratio(s1, s2): ...
def token_sort_ratio(s1, s2, force_ascii: bool = True, full_process: bool = True): ...
def partial_token_sort_ratio(s1, s2, force_ascii: bool = True, full_process: bool = True): ...
def token_set_ratio(s1, s2, force_ascii: bool = True, full_process: bool = True): ...
def partial_token_set_ratio(s1, s2, force_ascii: bool = True, full_process: bool = True): ...
def QRatio(s1, s2, force_ascii: bool = True, full_process: bool = True): ...
def UQRatio(s1, s2, full_process: bool = True): ...
def WRatio(s1, s2, force_ascii: bool = True, full_process: bool = True): ...
def UWRatio(s1, s2, full_process: bool = True): ...
