from . import fuzz as fuzz, utils as utils
from _typeshed import Incomplete
from collections.abc import Generator

default_scorer = fuzz.WRatio
default_processor = utils.full_process

def extractWithoutOrder(query, choices, processor=..., scorer=..., score_cutoff: int = 0) -> Generator[Incomplete, None, None]: ...
def extract(query, choices, processor=..., scorer=..., limit: int = 5): ...
def extractBests(query, choices, processor=..., scorer=..., score_cutoff: int = 0, limit: int = 5): ...
def extractOne(query, choices, processor=..., scorer=..., score_cutoff: int = 0): ...
def dedupe(contains_dupes, threshold: int = 70, scorer=...): ...
